export default {
    home: Symbol("/home"),
    orders: Symbol("/orders"),
    order: Symbol("/order"),
    settings: Symbol("/settings"),
    search: Symbol("/search"),
    product: Symbol("/product"),
    products: Symbol("/products"),
    editProduct: Symbol("/editProduct"),
    editCategory: Symbol("/editCategory"),
    cart: Symbol("/cart"),
    checkout: Symbol("/checkout"),
    confirmSubscribe: Symbol("/confirmSubscribe"),
    subscribe: Symbol("/subscribe"),
    coupons: Symbol("/coupons"),
    newCoupon: Symbol("/newCoupon"),
    pushNotifications: Symbol("/pushNotifications"),
    newPushNotification: Symbol("/newPushNotification"),
    tac: Symbol("/tac"),
    company: Symbol("/company"),
    profile: Symbol("/profile"),
    forgotPassword: Symbol("/forgotPassword"),
    layout: Symbol("/layout"),
    quotas: Symbol("/quotas"),
    newStaff: Symbol("/newStaff"),
    staff: Symbol("/staff"),
    subscription: Symbol("/subscription")
};